name: Deploy SRTech Website
on:
  push:
    branches:
      - main  # Trigger on push to main branch
permissions:
  contents: write  # Allows GitHub to push to gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload static content
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Deploy root files
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

